"""Knowledge domain models shared by every stage of the retrieval pipeline.

`Article` is the contract between article sources and the pipeline: every source
(extracted from the BARQ Operations Manual today, ServiceNow read-back later)
must normalize its data into this model, and chunking / embedding / ingestion
only ever see articles in this shape.

Vocabulary policy:
- ``workflow_state`` and ``security_level`` are closed enums — they mirror
  platform-level states and new values indicate a bug, not new data.
- ``category`` and ``service`` are an *open* controlled vocabulary — incoming
  data may legitimately introduce services or categories, so new slug-shaped
  values are accepted rather than rejected.
- Unknown extra fields are rejected. Normalization is the source's explicit
  job; this model never silently drops data it does not understand.
"""

import re
from enum import StrEnum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, field_validator

SLUG_PATTERN = re.compile(r"^[a-z0-9]+(?:[-_][a-z0-9]+)*$")
VERSION_PATTERN = re.compile(r"^\d+\.\d+$")
ARTICLE_NUMBER_PATTERN = re.compile(r"^KB\d+$")


class WorkflowState(StrEnum):
    """Lifecycle states mirrored from the ServiceNow KB workflow."""

    DRAFT = "draft"
    PUBLISHED = "published"
    RETIRED = "retired"


class SecurityLevel(StrEnum):
    """Audience levels used for Sprint 2 metadata filtering."""

    PUBLIC = "public"
    INTERNAL = "internal"
    RESTRICTED = "restricted"


class Article(BaseModel):
    """Canonical model for extracted knowledge base articles.

    Unique per-record key across versions is composed as
    ``f"{article_number}-v{version}"`` (e.g. ``KB0010-v1.0``).
    """

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    # Core article fields
    article_number: str = Field(
        ...,
        description="Article identifier, e.g. KB0001, KB0002",
    )
    version: str = Field(
        ...,
        pattern=VERSION_PATTERN.pattern,
        description="Article semver version, e.g. 1.0, 2.0",
    )
    title: str = Field(..., min_length=5, max_length=200)
    body: str = Field(
        ...,
        min_length=10,
        description="Canonical Markdown body with fenced code blocks",
    )
    short_description: str = Field(
        ...,
        max_length=255,
        description="One-line summary; 255 chars matches the ServiceNow kb_knowledge limit",
    )

    # 5 Mandatory metadata fields (payload-indexed in Qdrant)
    category: str = Field(
        ...,
        description="Controlled slug, e.g. network, software, hardware, inquiry",
    )
    service: str = Field(..., description="Service slug, e.g. corporate-vpn, sap-erp")
    workflow_state: WorkflowState
    security_level: SecurityLevel

    # ServiceNow lifecycle & optional metadata
    sys_id: str | None = Field(
        default=None,
        description="Generated by ServiceNow post-publishing (None prior to publish)",
    )
    owner: str | None = None
    reviewed_on: str | None = None
    related_records: list[str] = Field(default_factory=list)

    @field_validator("article_number")
    @classmethod
    def validate_article_number(cls, value: str) -> str:
        if not ARTICLE_NUMBER_PATTERN.match(value):
            raise ValueError(
                f"article_number must match {ARTICLE_NUMBER_PATTERN.pattern} "
                f"(e.g. KB0001), got {value!r}"
            )
        return value

    @field_validator("category", "service")
    @classmethod
    def validate_slug(cls, value: str) -> str:
        if not SLUG_PATTERN.match(value):
            raise ValueError(
                f"vocabulary values must be lowercase slugs matching "
                f"{SLUG_PATTERN.pattern}, got {value!r}"
            )
        return value

    @property
    def unique_key(self) -> str:
        """Unique identifier across versions, e.g. KB0010-v1.0."""
        return f"{self.article_number}-v{self.version}"

    @property
    def article_id(self) -> str:
        """Alias for unique_key for backwards compatibility with chunking & retrieval."""
        return self.unique_key


class ArticleChunk(BaseModel):
    """One retrievable piece of an article, produced by the chunker."""

    model_config = ConfigDict(frozen=True)

    article_id: str = Field(
        ...,
        description="Unique per-record key, e.g. KB0001-v1.0 or KB0010-v2.0",
    )
    chunk_index: int = Field(default=0, ge=0)
    total_chunks: int = Field(default=1, ge=1)
    section: str = Field(
        default="General",
        description="Header path the chunk belongs to, e.g. Resolution > Step 1",
    )
    text: str = Field(..., min_length=1)

    @property
    def chunk_id(self) -> str:
        """Deterministic chunk identifier, e.g. KB0001-v1.0#c0."""
        return f"{self.article_id}#c{self.chunk_index}"

    @classmethod
    def validate_bounds_model(cls, chunk_index: int, total_chunks: int) -> None:
        if chunk_index >= total_chunks:
            raise ValueError(f"chunk_index {chunk_index} must be < total_chunks {total_chunks}")

    def model_post_init(self, __context: Any) -> None:
        self.validate_bounds_model(self.chunk_index, self.total_chunks)


class KnowledgePayload(BaseModel):
    """Schema of a Qdrant point payload stored for each chunk."""

    model_config = ConfigDict(frozen=True)

    # Identity
    article_number: str
    version: str
    title: str
    sys_id: str | None = None

    # The 5 mandatory metadata fields (payload-indexed in Qdrant)
    category: str
    service: str
    workflow_state: WorkflowState
    security_level: SecurityLevel

    # Chunk position and retrievable text
    section: str
    chunk_index: int
    total_chunks: int
    chunk_text: str

    # Optional metadata & links
    owner: str | None = None
    related_records: list[str] = Field(default_factory=list)
    article_url: str | None = None

    @property
    def article_id(self) -> str:
        """Composed unique identifier, e.g. KB0010-v2.0."""
        return f"{self.article_number}-v{self.version}"

    @classmethod
    def from_chunk(cls, article: Article, chunk: ArticleChunk) -> "KnowledgePayload":
        """Build the payload for one chunk of an article."""
        return cls(
            article_number=article.article_number,
            version=article.version,
            title=article.title,
            sys_id=article.sys_id,
            category=article.category,
            service=article.service,
            workflow_state=article.workflow_state,
            security_level=article.security_level,
            section=chunk.section,
            chunk_index=chunk.chunk_index,
            total_chunks=chunk.total_chunks,
            chunk_text=chunk.text,
            owner=article.owner,
            related_records=list(article.related_records),
        )

    def to_qdrant_payload(self) -> dict[str, Any]:
        """Serialize for Qdrant: enums as values, unset optionals omitted."""
        data = self.model_dump(mode="json", exclude_none=True)
        # Include composed article_id for delete-by-article and grouping
        data["article_id"] = self.article_id
        return data
